import 'package:flutter/material.dart';
import 'package:numberwale/src/info/presentation/widgets/marketing_widgets.dart';

class _Faq {
  const _Faq(this.question, this.answer);

  final String question;
  final String answer;
}

class _FaqCategory {
  const _FaqCategory(this.title, this.faqs);

  final String title;
  final List<_Faq> faqs;
}

/// Mirrors the 6 categories and content at numberwale.com/faq.
const _categories = <_FaqCategory>[
  _FaqCategory('VIP Mobile Numbers - General & Basics', [
    _Faq(
      'What is a VIP or Fancy mobile number?',
      'A VIP or fancy mobile number is a unique 10-digit mobile sequence '
          'containing highly memorable patterns, repeated digits (like '
          '9999000000, 1234567890), or auspicious combinations. People buy '
          'VIP numbers to enhance their personal branding, boost business '
          'credibility, or align with numerological beliefs for good luck.',
    ),
    _Faq(
      'Why do people buy VIP mobile numbers?',
      'People buy VIP numbers primarily for Status & Branding (making a '
          'strong first impression), Easy Recall (crucial for business '
          'marketing, hoardings, and ads), and Numerology (choosing numbers '
          'that bring positive energy and success according to astrological '
          'beliefs). A premium number is essentially a lifelong digital asset.',
    ),
    _Faq(
      'Are the VIP numbers sold on Numberwale fresh or used?',
      'Numberwale ensures transparency. The majority of premium and '
          'ultra-premium numbers are completely fresh, unused combinations '
          'sourced legally. However, some extremely rare vintage numbers '
          '(like early 98 series) might have been previously owned but are '
          'legally disconnected, recycled, and fully cleared of any previous '
          'ties before being transferred to you.',
    ),
    _Faq(
      'What is the difference between a Fancy number and a Choice number?',
      'A Fancy number has a distinct visual or repeating pattern (e.g., '
          '88888, 786786) making it universally appealing. A Choice number '
          'doesn\'t necessarily have a repeating pattern but holds personal '
          'significance to the buyer, such as containing their Date of Birth '
          '(DOB), anniversary date, or a lucky vehicle number.',
    ),
  ]),
  _FaqCategory('Buying Process & Porting (MNP)', [
    _Faq(
      'How to buy a fancy mobile number online in India securely?',
      'Buying from Numberwale is 100% secure: 1) Search and select your '
          'desired number pattern. 2) Proceed to checkout and complete '
          'payment through the secure gateway. 3) Numberwale generates and '
          'sends the Unique Porting Code (UPC) and invoice within 24 hours. '
          '4) Visit any local operator store (Jio, Airtel, Vi) with Aadhar '
          'card and the UPC to port the number under your name.',
    ),
    _Faq(
      'What is a Unique Porting Code (UPC) and why do I need it?',
      'The Unique Porting Code is an 8-digit alphanumeric code generated by '
          'the telecom operator. It is legally required to transfer (port) a '
          'mobile number from one network to another, or from Numberwale\'s '
          'inventory to your personal name. It acts as the legal '
          'authorization for the transfer.',
    ),
    _Faq(
      'How long does it take to activate a fancy mobile number?',
      'Once you receive the UPC and submit it at your local telecom '
          'operator store (along with e-KYC), the standard Mobile Number '
          'Portability (MNP) activation takes 3 to 5 business days for '
          'same-circle transfers, and up to 5-7 days for inter-circle '
          'transfers.',
    ),
    _Faq(
      'Do I need to visit a store to activate my VIP number?',
      'Yes. While purchasing the number is done 100% online through '
          'Numberwale, the final step requires physically visiting your '
          'chosen telecom operator\'s retail store (Jio, Airtel, Vi, BSNL). '
          'You must present your ID (Aadhar Card) for mandatory e-KYC '
          'fingerprint verification to legally register the number in your '
          'name.',
    ),
    _Faq(
      'What happens if my UPC code expires before porting?',
      'A standard UPC code is valid for 4 days (up to 15 days for certain '
          'regions like J&K and North East). If unable to visit a store '
          'within this timeframe and the code expires, simply contact '
          'Numberwale support, and they will generate and provide a fresh '
          'UPC code at no extra cost.',
    ),
    _Faq(
      'Can I port a number if I live in a different state (Inter-circle '
          'roaming)?',
      'Yes. Due to India\'s \'One Nation, One Number\' MNP policy, you can '
          'purchase a number originating from any telecom circle (e.g., '
          'Delhi, Mumbai, Gujarat) and successfully port it to your local '
          'state and operator. There are no roaming charges for incoming '
          'calls anywhere in India.',
    ),
    _Faq(
      'Do you sell prepaid or postpaid fancy numbers?',
      'The numbers Numberwale sells are flexible. When customers visit the '
          'telecom operator store for porting, they can instruct them to '
          'activate the number as either Prepaid or Postpaid connection, '
          'depending entirely on personal preference.',
    ),
  ]),
  _FaqCategory('Networks & Compatibility', [
    _Faq(
      'Can I port my VIP number to any network (Jio, Airtel, Vi, BSNL)?',
      'Absolutely. Once Numberwale provides the UPC, the number is '
          'completely network-agnostic. Customers have full freedom to port '
          'the VIP number to any telecom operator of choice — be it '
          'Reliance Jio, Bharti Airtel, Vodafone Idea (Vi), or BSNL.',
    ),
    _Faq(
      'Will my VIP number work on a 5G network?',
      'Yes. The 5G compatibility depends entirely on the telecom operator '
          'chosen during porting and your mobile handset. The VIP number '
          'itself places no restrictions. If you port to a 5G-enabled '
          'network like Jio or Airtel and have a 5G phone, your number will '
          'function seamlessly on 5G.',
    ),
    _Faq(
      'Can I convert my fancy number into an eSIM?',
      'Yes. Once the physical SIM is successfully activated in your name '
          'after porting, you can easily place a request with your telecom '
          'operator (like Airtel or Jio) to convert the physical SIM into an '
          'eSIM via their standard SMS or app-based process.',
    ),
  ]),
  _FaqCategory('Pricing, Payments & Security', [
    _Faq(
      'What payment methods do you accept for buying a number?',
      'Numberwale accepts all 100% secure, RBI-approved payment methods '
          'including UPI (Google Pay, PhonePe, Paytm), all major Credit/Debit '
          'Cards (Visa, Mastercard, RuPay), Net Banking across 50+ Indian '
          'banks, and Wallet payments.',
    ),
    _Faq(
      'Do you offer EMIs or installment plans for premium numbers?',
      'Yes. For high-value VVIP numbers, Numberwale offers flexible EMI '
          'options during checkout via supported Credit Cards. Customers can '
          'choose to split payment into manageable monthly installments of '
          '3, 6, 9, or 12 months.',
    ),
    _Faq(
      'What is your refund policy if the number fails to port?',
      'Numberwale offers a 100% Money-Back Guarantee. If, for any '
          'unforeseen technical or legal reason from the operator\'s side, '
          'the VIP number fails to port to your name and the issue cannot be '
          'resolved by their support team, they will process a full, '
          'hassle-free refund to your original payment method.',
    ),
    _Faq(
      'How does Numberwale guarantee the security of my transaction?',
      'Numberwale is a registered, trusted entity operating fully within '
          'TRAI guidelines. The website uses industry-standard 256-bit SSL '
          'encryption. They never store card details, and all payments are '
          'processed through heavily audited, secure payment gateways. '
          'Proper GST invoices are provided for every purchase.',
    ),
    _Faq(
      'Why are some mobile numbers so expensive (like 0000 or 786)?',
      'Prices are dictated by rarity, demand, and visual symmetry. Out of '
          'millions of combinations, there are very few \'Tetra 0000\' or '
          '\'Hexa\' sequences. High demand from businesses, celebrities, and '
          'numerologists for these ultra-rare, mathematically perfect '
          'sequences drives their market value up.',
    ),
    _Faq(
      'Is there a monthly maintenance fee for a VIP number?',
      'No. The amount paid to Numberwale is a one-time fee to acquire '
          'ownership of the number. After activation, customers only pay '
          'their chosen telecom operator for regular monthly recharge or '
          'postpaid bill, just like any normal mobile number.',
    ),
  ]),
  _FaqCategory('Types of VIP Numbers', [
    _Faq(
      'Do you sell Islamic 786 mobile numbers?',
      'Yes, 786 numbers are highly sought after for their religious and '
          'auspicious significance. Numberwale maintains a dedicated, '
          'massive inventory of these. Customers can easily search for '
          'numbers ending in 786, starting with 786, or featuring multiple '
          '786 sequences (like 786786).',
    ),
    _Faq(
      'What is a mirror mobile number?',
      'A mirror mobile number is essentially a palindrome — a number that '
          'reads the exact same forwards and backwards (e.g., 90022 22009). '
          'They are visually stunning, incredibly rare, and very easy for '
          'clients to memorize.',
    ),
    _Faq(
      'What are Hexa, Hepta, and Octa numbers?',
      'These refer to the number of times a single digit repeats '
          'consecutively. Hexa: A digit repeats 6 times (e.g., 999999). '
          'Hepta: A digit repeats 7 times (e.g., 8888888). Octa: A digit '
          'repeats 8 times (e.g., 77777777). These are the rarest and most '
          'expensive \'VVIP\' tier numbers.',
    ),
    _Faq(
      'Can I get a mobile number matching my Date of Birth (DOB) or '
          'Anniversary?',
      'Yes. Using Numberwale\'s \'Customize Your Number\' feature, you can '
          'input your exact 4-digit, 6-digit, or 8-digit date (like '
          '14021995 for Feb 14, 1995). The system will immediately scan the '
          'nationwide database to find numbers containing your special date.',
    ),
    _Faq(
      'Can I get a VIP number for my business or enterprise team?',
      'Absolutely. For businesses, Numberwale offers \'Family Packs\' or '
          '\'Corporate Packs\', which allow buying consecutive or matching '
          'sequential numbers (e.g., 989800001, 989800002). This provides '
          'unmatched brand uniformity for sales and support teams.',
    ),
  ]),
  _FaqCategory('Numerology & Astrology', [
    _Faq(
      'What is mobile number numerology?',
      'Mobile numerology analyzes the total sum and specific combinations '
          'of digits in your mobile number to determine its energy '
          'vibration. Since you carry your phone everywhere, numerologists '
          'believe that a number vibrating in harmony with your life path '
          'can attract wealth, health, and success.',
    ),
    _Faq(
      'Can a lucky mobile number bring success in business?',
      'In numerology, certain numbers (like totals of 1, 3, 5, or 6) are '
          'strongly associated with leadership, communication, wealth, and '
          'expansion. Many top businessmen, politicians, and celebrities '
          'consult numerologists to select numbers that align perfectly with '
          'their business names and goals.',
    ),
    _Faq(
      'How is the numerology score or sum of a mobile number calculated?',
      'The simplest method is adding all 10 digits together until you '
          'reach a single digit. For example, if a number adds up to 51, you '
          'further add 5 + 1 = 6. The number 6 is ruled by Venus, '
          'representing luxury and wealth. Numberwale\'s platform calculates '
          'these sums automatically for every listed number.',
    ),
    _Faq(
      'Do you offer personalized lucky number consultations?',
      'Yes. Numberwale\'s expert numerology team offers personalized '
          'consultations. By analyzing your full name and Date of Birth, '
          'they generate a comprehensive Lo Shu Grid report and suggest the '
          'exact mobile number sequences that will harmonize with your '
          'destiny and mitigate negative energies.',
    ),
  ]),
];

/// Mirrors the FAQ content and accordion styling at numberwale.com/faq.
class FaqPage extends StatelessWidget {
  const FaqPage({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text('FAQs'),
        centerTitle: true,
      ),
      body: MarketingBackground(
        child: ListView(
          padding: const EdgeInsets.all(20),
          children: [
            Text(
              'Frequently Asked Questions',
              textAlign: TextAlign.center,
              style: theme.textTheme.headlineSmall?.copyWith(
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 8),
            Text(
              'Everything you need to know about buying a premium VIP '
              'mobile number with Numberwale.',
              textAlign: TextAlign.center,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: theme.colorScheme.onSurfaceVariant,
              ),
            ),
            const SizedBox(height: 24),
            for (var i = 0; i < _categories.length; i++)
              _CategoryAccordion(
                category: _categories[i],
                initiallyExpanded: i == 0,
              ),
          ],
        ),
      ),
    );
  }
}

class _CategoryAccordion extends StatefulWidget {
  const _CategoryAccordion({
    required this.category,
    this.initiallyExpanded = false,
  });

  final _FaqCategory category;
  final bool initiallyExpanded;

  @override
  State<_CategoryAccordion> createState() => _CategoryAccordionState();
}

class _CategoryAccordionState extends State<_CategoryAccordion> {
  late bool _expanded = widget.initiallyExpanded;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final shape = RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(18),
      side: BorderSide.none,
    );

    return Container(
      margin: const EdgeInsets.only(bottom: 14),
      decoration: BoxDecoration(
        color: theme.colorScheme.surface,
        borderRadius: BorderRadius.circular(18),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.04),
            blurRadius: 12,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Theme(
        data: theme.copyWith(dividerColor: Colors.transparent),
        child: ExpansionTile(
          initiallyExpanded: widget.initiallyExpanded,
          onExpansionChanged: (v) => setState(() => _expanded = v),
          shape: shape,
          collapsedShape: shape,
          tilePadding: const EdgeInsets.fromLTRB(20, 4, 16, 4),
          childrenPadding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
          title: Text(
            widget.category.title,
            style: theme.textTheme.titleMedium?.copyWith(
              fontWeight: FontWeight.bold,
            ),
          ),
          trailing: Container(
            width: 32,
            height: 32,
            decoration: BoxDecoration(
              color: theme.colorScheme.primary,
              shape: BoxShape.circle,
            ),
            child: Icon(
              _expanded ? Icons.remove : Icons.add,
              color: Colors.white,
              size: 18,
            ),
          ),
          children: [
            for (final faq in widget.category.faqs)
              Container(
                width: double.infinity,
                margin: const EdgeInsets.only(bottom: 12),
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: theme.colorScheme.surfaceContainerHigh,
                  borderRadius: BorderRadius.circular(14),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    RichText(
                      text: TextSpan(
                        children: [
                          TextSpan(
                            text: 'Q.  ',
                            style: theme.textTheme.bodyMedium?.copyWith(
                              color: theme.colorScheme.primary,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                          TextSpan(
                            text: faq.question,
                            style: theme.textTheme.bodyMedium?.copyWith(
                              color: theme.colorScheme.onSurface,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 8),
                    RichText(
                      text: TextSpan(
                        children: [
                          TextSpan(
                            text: 'A.  ',
                            style: theme.textTheme.bodyMedium?.copyWith(
                              color: theme.colorScheme.onSurfaceVariant,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                          TextSpan(
                            text: faq.answer,
                            style: theme.textTheme.bodyMedium?.copyWith(
                              color: theme.colorScheme.onSurfaceVariant,
                              height: 1.4,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
          ],
        ),
      ),
    );
  }
}
